export enum ActionTypes {
  FETCH_TRAININGS_TYPES = 'FETCH_TRAININGS_TYPES',
  FETCH_TRAININGS_TYPES_SUCCESS = 'FETCH_TRAININGS_TYPES_SUCCESS',
  FETCH_TRAININGS_TYPES_ERROR = 'FETCH_TRAININGS_TYPES_ERROR',

  EDIT_TRAINING = 'EDIT_TRAINING',
  EDIT_TRAINING_SUCCESS = 'EDIT_TRAINING_SUCCESS',
  EDIT_TRAINING_ERROR = 'EDIT_TRAINING_ERROR',

  FETCH_TRAININGS = 'FETCH_TRAINING',
  FETCH_TRAININGS_SUCCESS = 'FETCH_TRAINING_SUCCESS',
  FETCH_TRAININGS_ERROR = 'FETCH_TRAININGS_ERROR',

  CREATE_TRAINING = 'CREATE_TRAINING',
  CREATE_TRAINING_SUCCESS = 'CREATE_TRAINING_SUCCESS',
  CREATE_TRAINING_ERROR = 'CREATE_TRAINING_ERROR',

  DELETE_TRAINING = 'DELETE_TRAINING',
  DELETE_TRAINING_SUCCESS = 'DELETE_TRAINING_SUCCESS',
  DELETE_TRAINING_ERROR = 'DELETE_TRAINING_ERROR',

  UPDATE_TRAINING = 'UPDATE_TRAINING',
  UPDATE_TRAINING_SUCCESS = 'UPDATE_TRAINING_SUCCESS',
  UPDATE_TRAINING_ERROR = 'UPDATE_TRAINING_ERROR',

  SET_DATE_SORT = 'SET_DATE_SORT',
  SET_DISTANCE_SORT = 'SET_DISTANCE_SORT',

  RESET_STATE = 'RESET_STATE',
}